// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADNO8xte572Jdm6BOHl-T1WTMQrMiI2NU',
    appId: '1:918634657920:web:397bca0d2ff7c84cd78e65',
    messagingSenderId: '918634657920',
    projectId: 'projest-b4ef1',
    authDomain: 'projest-b4ef1.firebaseapp.com',
    storageBucket: 'projest-b4ef1.firebasestorage.app',
    measurementId: 'G-S2NSB7XXHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJx0tOWW8lFKCfqUcVZi2haEKJCYxbWyU',
    appId: '1:918634657920:android:4bd231a9c0f9dbced78e65',
    messagingSenderId: '918634657920',
    projectId: 'projest-b4ef1',
    storageBucket: 'projest-b4ef1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChaOOh7wQ7XydwYVfPgDX_8A2usPBIDco',
    appId: '1:918634657920:ios:056b6de15590bfead78e65',
    messagingSenderId: '918634657920',
    projectId: 'projest-b4ef1',
    storageBucket: 'projest-b4ef1.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChaOOh7wQ7XydwYVfPgDX_8A2usPBIDco',
    appId: '1:918634657920:ios:056b6de15590bfead78e65',
    messagingSenderId: '918634657920',
    projectId: 'projest-b4ef1',
    storageBucket: 'projest-b4ef1.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADNO8xte572Jdm6BOHl-T1WTMQrMiI2NU',
    appId: '1:918634657920:web:df6341ba2acf3d10d78e65',
    messagingSenderId: '918634657920',
    projectId: 'projest-b4ef1',
    authDomain: 'projest-b4ef1.firebaseapp.com',
    storageBucket: 'projest-b4ef1.firebasestorage.app',
    measurementId: 'G-F6DLY8MP8X',
  );
}
